node("jjb") {
  def app


  stage('Clone repository') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [],
      submoduleCfg: [],
      userRemoteConfigs: [[
        credentialsId: '088d3940-55c4-4d8c-85c5-007886b9555c',
        url: 'git@github.com:ikhripunov/connect-simple-todos-app.git'
      ]]
    ])
  }

  stage('Build backend') {
    sh '''
      cd swagger-backend;
      yarn install;
      yarn generate-api-interface;
      yarn compile;
    '''
  }

  stage('Build image') {
    sh '''
      cp jobs/backend/pipeline/Dockerfile ./Dockerfile;
    '''
    app = docker.build("simple-backend")
  }

  stage('Test image') {
    app.inside {
      sh 'This is a test!'
    }
  }

  stage('Push image') {
    echo 'Push image'
    docker.withRegistry('http://docker-registry.connect.cd:5000/v2/_catalog', 'registry-creds') {
      app.push("${env.BUILD_NUMBER}")
      app.push("latest")
    }
  }

  stage('Clean existing image') {
    sh "docker rmi docker-image"
  }
}