node("jjb") {
  def app


  environment {
    DOCKER_HOST = 'tcp://localhost:2375'
  }

  stage('Clone repository') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [],
      submoduleCfg: [],
      userRemoteConfigs: [[
        credentialsId: '088d3940-55c4-4d8c-85c5-007886b9555c',
        url: 'git@github.com:ikhripunov/connect-simple-todos-app.git'
      ]]
    ])
  }

  stage('Build backend') {
    sh '''
      cd swagger-backend;
      yarn install;
      yarn generate-api-interface;
      yarn compile;
    '''
  }

  stage('Build image') {
    sh '''
      cp jobs/backend/pipeline/Dockerfile ./Dockerfile;
    '''
    docker.withServer('tcp://localhost:2375') {
      app = docker.build('docker-registry.connect.cd/ikhripunov/simple-backend')
    }
  }

  stage('Push image') {
    kubernetes.image().withName("docker-registry.connect.cd/ikhripunov/simple-backend").push().toRegistry()
  }

  stage('Deploy') {
    sh '''
      kubectl apply -f jobs/backend/pipeline/backend.yml;
      kubectl apply -f jobs/backend/pipeline/service.yml;
    '''
  }

  stage('Clean existing image') {
    sh '''
      docker rmi ikhripunov/simple-backend
    '''
  }
}