node {

  def app
  stage('Clone repository') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [],
      submoduleCfg: [],
      userRemoteConfigs: [[
        url: 'git@github.com:ikhripunov/connect-simple-todos-app.git'
      ]]
    ])
  }

  stage('Build backend') {
    sh '''
      cd swagger-backend;
      yarn install
      yarn generate-api-interface
      yarn compile
    '''
  }

  stage('Build image') {
    app = docker.build("docker-image")
  }

  stage('Test image') {
    sh '''
      if ! docker inspect docker-image &> /dev/null; then
        echo 'docker-image does not exist!'
      exit 1
    fi
    '''
  }

  stage('Push image') {
    echo 'Push image'
    docker.withRegistry('https://local-registry:9666', 'registry-creds') {
      app.push("${env.BUILD_NUMBER}")
      app.push("latest")
    }
  }

  stage('Clean existing image') {
    sh "docker rmi docker-image"
  }
}