node("jjb") {
  def app

  stage('Clone repository') {
    checkout([
      $class: 'GitSCM',
      branches: [[name: '*/master']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [],
      submoduleCfg: [],
      userRemoteConfigs: [[
        credentialsId: 'jenkins-clearpoint',
        url: 'git@github.com:ikhripunov/connect-simple-todos-app.git'
      ]]
    ])
  }

  stage('Build frontend') {
    sh '''
      cd swagger-frontend;
      yarn install;
      yarn generate-api-client;
      yarn build --production;
    '''
  }

  stage('Build image') {
    sh '''
      cp jobs/frontend/pipeline/Dockerfile ./Dockerfile;
    '''
    app = docker.build('ikhripunov/simple-frontend')
  }

  stage('Test image') {
    app.withRun {
      echo 'This is a test!'
    }
  }

  stage('Push image') {
    withCredentials([[$class: 'UsernamePasswordMultiBinding',
                            credentialsId: 'registry-creds',
                            usernameVariable: 'DOCKER_HUB_USER',
                            passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
      sh '''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD;
        docker push ikhripunov/simple-frontend;
      '''
    }
  }

  stage('Deploy') {
    sh '''
      kubectl apply -f jobs/frontend/pipeline/frontend.yml;
      kubectl apply -f jobs/frontend/pipeline/service.yml;
    '''
  }

  stage('Clean existing image') {
    sh '''
      docker rmi ikhripunov/simple-frontend
    '''
  }
}